<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HarvestManor</RootNamespace>
    <AssemblyName>HarvestManor</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GodotProjectDir>$(MSBuildProjectDirectory)</GodotProjectDir>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove=".godot/**" />
    <EmbeddedResource Remove=".godot/**" />
    <None Remove=".godot/**" />
  </ItemGroup>
</Project>
